services:
  oracle:
    image: gvenzl/oracle-free:23.3-slim-faststart
    environment:
    - ORACLE_PASSWORD=P4ssword!
    ports:
    - 1522:1521
    healthcheck:
      test:
      - CMD
      - /opt/oracle/healthcheck.sh
      interval: 5s
      timeout: 5s
      retries: 20
